### ISSUE TITLE
About original palm vein data

### ISSUE THREAD

**Issue by mengtongo** [ljs1214/palm-vein-recognize#1]
Hi, could you please provide me the original data? Thank you!

**Comment by ljs1214** [comment]
I have just uploaded the datasets into drive.google. 

In the NIR folder, each folder represents palmprint information from the same person, starting with a 1 or 2 to indicate the left and right hand.

In the ROI dataset, the two sessions represent two palm vein acquisitions several days apart. In each session, every 6th image is from the same palm.

You can find the datasets by following:
https://drive.google.com/file/d/1MlHJhfZwzuMe3UCj9wkXIBN2d4nKyU7d/view?usp=sharing, https://drive.google.com/file/d/1bQxzBLYX4t6YXzMgh03m8vuMPMYUPFOV/view?usp=sharing

**Comment by mengtongo** [comment]
I got it, thank you very much!
